apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ai-app
spec:
  selector:
    matchLabels:
      app: my-ai-app
  replicas: 2
  template:
    metadata:
      labels:
        app: my-ai-app
    spec:
      containers:
      - name: my-ai-app
        image: muralikrishna632/my-ai-app:latest
        ports:
        - containerPort: 5000
